// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace PrefabricatedPanels
{
    public class PrefabricatedPanelsInputs: S3Args
    {
		/// <summary>
		/// The spacing of the studs on center.
		/// </summary>
		[JsonProperty("Stud Spacing")]
		public double StudSpacing {get;}

		/// <summary>
		/// Should wall board be generated?
		/// </summary>
		[JsonProperty("Create Wall Board")]
		public bool CreateWallBoard {get;}


        
        /// <summary>
        /// Construct a PrefabricatedPanelsInputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public PrefabricatedPanelsInputs() : base()
        {
			this.StudSpacing = 1;
			this.CreateWallBoard = false;

        }


        /// <summary>
        /// Construct a PrefabricatedPanelsInputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public PrefabricatedPanelsInputs(double studspacing, bool createwallboard, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey): base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
			this.StudSpacing = studspacing;
			this.CreateWallBoard = createwallboard;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}