// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Collections.Generic;

namespace PrefabricatedPanels
{
    public class PrefabricatedPanelsOutputs: ResultsBase
    {
		/// <summary>
		/// The total number of panels generated.
		/// </summary>
		[JsonProperty("Total Panels")]
		public double TotalPanels {get;}

		/// <summary>
		/// The total length of framing generated.
		/// </summary>
		[JsonProperty("Total Length of Framing")]
		public double TotalLengthOfFraming {get;}


        
        /// <summary>
        /// Construct a PrefabricatedPanelsOutputs with default inputs.
        /// This should be used for testing only.
        /// </summary>
        public PrefabricatedPanelsOutputs() : base()
        {

        }


        /// <summary>
        /// Construct a PrefabricatedPanelsOutputs specifying all inputs.
        /// </summary>
        /// <returns></returns>
        [JsonConstructor]
        public PrefabricatedPanelsOutputs(double totalpanels, double totallengthofframing): base()
        {
			this.TotalPanels = totalpanels;
			this.TotalLengthOfFraming = totallengthofframing;

		}

		public override string ToString()
		{
			var json = JsonConvert.SerializeObject(this);
			return json;
		}
	}
}